FROM public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12

COPY docker/fluent-bit/ecs/fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
COPY docker/fluent-bit/ecs/parsers.conf /fluent-bit/etc/parsers.conf

USER root
RUN yum update -y && yum install -y curl

EXPOSE 2020

CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]