FROM nginx:1.24

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx/ecs/default.conf /etc/nginx/conf.d/default.conf

COPY public /var/www/html/public

RUN chown -R nginx:nginx /var/www/html \
    && chmod -R 755 /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]