name: cicd

on:
  push:
    branches:
      - main

env:
  IMG_TAG: ${{ github.sha }}

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::031215319865:role/githubRole

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/php/ecs/dockerfile
          platforms: linux/amd64
          push: true
          tags: public.ecr.aws/v9g2r9e2/wwwtskt/laravel:${{ env.IMG_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-taskdef:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::031215319865:role/githubRole

      - name: Install ecspresso
        run: |
          curl -sSL https://github.com/kayac/ecspresso/releases/latest/download/ecspresso-linux-amd64.tar.gz \
          | tar xz
          sudo mv ecspresso /usr/local/bin/

      - name: Register new task definition revision
        run: |
          ecspresso register --config ecspresso/ecspresso.yml
      # s3にappspecをプッシュする
      # code deployを実行する
