name: cicd

on:
  push:
    branches:
      - main

jobs:
  doker-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::031215319865:role/githubRole

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/php/ecs/dockerfile
          platforms: linux/amd64
          push: true
          tags: public.ecr.aws/v9g2r9e2/wwwtskt/laravel:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # s3にappspecをプッシュする
      # code deployを実行する
